"""initial schema

Revision ID: ca78d72fe55e
Revises: 
Create Date: 2026-09-17 09:30:38.381712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca78d72fe55e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('muscle_group', sa.String(length=64), nullable=False),
    sa.Column('secondary_muscles', sa.String(length=255), nullable=True),
    sa.Column('equipment', sa.String(length=64), nullable=False),
    sa.Column('mechanic', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('form_instructions', sa.Text(), nullable=False),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_exercises_name')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_muscle_group'), ['muscle_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_slug'), ['slug'], unique=True)

    op.create_table('ped_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('aliases', sa.String(length=255), nullable=True),
    sa.Column('compound_class', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('administration_route', sa.String(length=64), nullable=True),
    sa.Column('half_life', sa.String(length=64), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=False),
    sa.Column('claimed_effects', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('cardiovascular_risk', sa.Text(), nullable=False),
    sa.Column('endocrine_risk', sa.Text(), nullable=False),
    sa.Column('hepatic_risk', sa.Text(), nullable=False),
    sa.Column('other_risks', sa.Text(), nullable=True),
    sa.Column('legal_status', sa.Text(), nullable=False),
    sa.Column('medical_supervision_required', sa.Boolean(), nullable=False),
    sa.Column('harm_reduction_notes', sa.Text(), nullable=False),
    sa.Column('monitoring_bloodwork', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ped_profiles_name')
    )
    with op.batch_alter_table('ped_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ped_profiles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ped_profiles_compound_class'), ['compound_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_ped_profiles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ped_profiles_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('goal_calories', sa.Float(), nullable=False),
    sa.Column('goal_protein_g', sa.Float(), nullable=False),
    sa.Column('goal_carbs_g', sa.Float(), nullable=False),
    sa.Column('goal_fats_g', sa.Float(), nullable=False),
    sa.Column('goal_fiber_g', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('macro_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_logs_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_logs_logged_on'), ['logged_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_macro_logs_logged_on'))
        batch_op.drop_index(batch_op.f('ix_macro_logs_barcode'))

    op.drop_table('macro_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ped_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ped_profiles_slug'))
        batch_op.drop_index(batch_op.f('ix_ped_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_ped_profiles_compound_class'))
        batch_op.drop_index(batch_op.f('ix_ped_profiles_category'))

    op.drop_table('ped_profiles')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_slug'))
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_muscle_group'))
        batch_op.drop_index(batch_op.f('ix_exercises_equipment'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
